<?php

include_once ('oeuvre.class.php');

class OeuvreEnVente extends oeuvre
{
    private $_etat;
    private $_prixReel;

    public function __construct($_numeroOeuvre, $_titreOeuvre, $unPrix)
    {
        parent::__construct($_numeroOeuvre, $_titreOeuvre);
        $this->_prixReel = $unPrix;
        $this->_etat = 'L';
    }

    public function setLibre()
    {
        $this->_etat= 'L';
    }

    public function setReserve()
    {
        $this ->_etat = 'R';
    }

    /**
     * @return mixed
     */
    public function getEtat()
    {
        return $this->_etat;
    }

    /**
     * @param mixed $etat
     */
    public function setEtat($etat)
    {
        $this->_etat = $etat;
    }

    /**
     * @return mixed
     */
    public function getPrixReel()
    {
        return $this->_prixReel;
    }

    /**
     * @param mixed $prixReel
     */
    public function setPrixReel($prixReel)
    {
        $this->_prixReel = $prixReel;
    }

    public function RetourInfo()
    {
        return parent::RetourInfo(). "etat : ". $this->_etat. "Prix : ".$this->_prixReel; // TODO: Change the autogenerated stub
    }
}